/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsDag = Dag
/**
 * Directed acyclic graph with arbitrary JSON metadata on nodes and edges.
 *
 * Node IDs and edge IDs are returned as plain JavaScript `number` values.
 * When passed back into methods, they must be **non-negative integers** within
 * JavaScript’s safe integer range (`Number.MIN_SAFE_INTEGER` …
 * `Number.MAX_SAFE_INTEGER`); non-integers and out-of-range values are rejected.
 */
export declare class Dag {
  /** Create an empty DAG. */
  constructor()
  /**
   * Add a node carrying `meta` (any JSON value).
   * Returns the numeric node ID.
   */
  addNode(meta: any): number
  /** Remove a node and all its incident edges. */
  removeNode(id: number): void
  /**
   * Add a directed edge `from → to` carrying `meta`.
   * Throws if the edge would create a cycle or if the edge already exists.
   */
  addEdge(from: number, to: number, meta: any): number
  /** Remove a single edge by ID, leaving its endpoint nodes intact. */
  removeEdge(id: number): void
  /** All node IDs currently in the graph (unordered). */
  nodes(): Array<number>
  /** All edge IDs currently in the graph (unordered). */
  edges(): Array<number>
  /** Return the `[from, to]` endpoint node IDs of edge `id`. */
  edgeEndpoints(id: number): Array<number>
  /** Return all ancestors of `id` (nodes from which it is reachable). */
  ancestors(id: number): Array<number>
  /** Return all descendants of `id` (nodes reachable from it). */
  descendants(id: number): Array<number>
  /** Nodes with no incoming edges. */
  roots(): Array<number>
  /** Nodes with no outgoing edges. */
  leaves(): Array<number>
  /** A valid topological ordering of all nodes. */
  topologicalSort(): Array<number>
  /** Whether there is a directed path from `from` to `to`. */
  hasPath(from: number, to: number): boolean
  /** Return the metadata of node `id`. */
  nodeMeta(id: number): any
  /** Replace the metadata of node `id`. */
  setNodeMeta(id: number, meta: any): void
  /** Return the metadata of edge `id`. */
  edgeMeta(id: number): any
  /** Replace the metadata of edge `id`. */
  setEdgeMeta(id: number, meta: any): void
  /**
   * Serialize the DAG to a JSON string.
   *
   * The format preserves exact node and edge IDs so a round-trip via
   * `Dag.fromJson` restores the same IDs.
   */
  toJson(): string
  /** Deserialize a DAG from a JSON string produced by `toJson`. */
  static fromJson(s: string): JsDag
}
