/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsDag = Dag
/**
 * Directed acyclic graph with arbitrary JSON metadata on nodes and edges.
 *
 * Node IDs and edge IDs are returned as plain JavaScript `number` values.
 * They are safe to use as numbers for any practical graph size (values stay
 * well below 2^53).
 */
export declare class Dag {
  /** Create an empty DAG. */
  constructor()
  /**
   * Add a node carrying `meta` (any JSON value).
   * Returns the numeric node ID.
   */
  addNode(meta: any): number
  /** Remove a node and all its incident edges. */
  removeNode(id: number): void
  /**
   * Add a directed edge `from → to` carrying `meta`.
   * Throws if the edge would create a cycle.
   */
  addEdge(from: number, to: number, meta: any): number
  /** Return all ancestors of `id` (nodes from which it is reachable). */
  ancestors(id: number): Array<number>
  /** Return all descendants of `id` (nodes reachable from it). */
  descendants(id: number): Array<number>
  /** Nodes with no incoming edges. */
  roots(): Array<number>
  /** Nodes with no outgoing edges. */
  leaves(): Array<number>
  /** A valid topological ordering of all nodes. */
  topologicalSort(): Array<number>
  /** Whether there is a directed path from `from` to `to`. */
  hasPath(from: number, to: number): boolean
  /** Return the metadata of node `id`. */
  nodeMeta(id: number): any
  /** Replace the metadata of node `id`. */
  setNodeMeta(id: number, meta: any): void
  /** Return the metadata of edge `id`. */
  edgeMeta(id: number): any
  /** Replace the metadata of edge `id`. */
  setEdgeMeta(id: number, meta: any): void
}
